language: node_js
node_js:
  - "10"
sudo: required
env:
  global: 
    - CC_TEST_REPORTER_ID=d5585b59bad3929446793bef5ce8ed98f8ec6b3e5ebdde8b2546aa293c8e04c9

install:
  - npm install

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

script:
  - npm run coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT