openapi: 3.0.0
info:
  version: 1.0.0
  title: governify-cep-connector
  description: >-
    Governify Cep Connector Service
  contact:
    name: ISA Research Group
    email: 'isagroup.us@gmail.com's
    url: 'http://www.isa.us.es/'
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
paths:
  '/api/v1/github/':
    post:
      description: Stores data from GitHub to be processed by the CEP
      operationId: addGithubData
      responses:
        '200':
          description: Github data received
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
      requestBody:
        x-name: data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/data'
        description: Data to be processed by the CEP
        required: true
  '/api/v1/pivotal/':
    post:
      description: Stores data from Pivotal to be processed by the CEP
      operationId: addPivotalData
      responses:
        '200':
          description: Pivotal data received
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
      requestBody:
        x-name: data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/data'
        description: Data to be processed by the CEP
        required: true
  '/api/v1/poker/':
    post:
      description: Stores data from Poker Planning to be processed by the CEP
      operationId: addPokerData
      responses:
        '200':
          description: Poker Planning data received
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
      requestBody:
        x-name: data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/data'
        description: Data to be processed by the CEP
        required: true
  '/api/v1/posfacto/':
    post:
      description: Stores data from Posfacto to be processed by the CEP
      operationId: addPosfactoData
      responses:
        '200':
          description: Posfacto data received
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
      requestBody:
        x-name: data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/data'
        description: Data to be processed by the CEP
        required: true
components:
  schemas:
    errorModel:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    data:
      description: 'Json data from an API'
      type: object
      properties: {}
